version: '3'
services:

  loyalty_service:
    container_name: loyalty_service
    build:
      context: loyalty_service/
      dockerfile: Dockerfile
    depends_on:
      - loyalty-postgres
      - loyalty-rabbit
    env_file:
      - .env
    restart: always
    ports:
      - 6666:6666

  loyalty-postgres:
    container_name: loyalty-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${LOYALTY_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${LOYALTY_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${LOYALTY_POSTGRES_DB_NAME}
    volumes:
      - loyalty_pgdata:/var/lib/postgresql/data
    expose:
      - "5438"
    command: -p 5438

  loyalty-rabbit:
    image: rabbitmq:3.9-management
    container_name: loyalty-rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    logging:
      driver: none
    restart: always

  admin-panel:
    depends_on:
      - loyalty-postgres
    build:
      context: admin_panel
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8012:8000

volumes:
  loyalty_pgdata:
  rabbitmq_data:
  rabbitmq_log:
  loyalty-logs:
  nginx-logs:
