version: '3'
services:


  loyalty-service:
    build:
        context: loyalty_service
    container_name: loyalty-service
    env_file:
      - .env
    ports:
      - "6666:6666"
    volumes:
        - loyalty-logs:/opt/app/src/logs
    depends_on:
      - loyalty-postgres
      - loyalty-rabbit

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 8088:8088
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx/
    depends_on:
      - loyalty-service

  loyalty-postgres:
    container_name: loyalty-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${LOYALTY_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${LOYALTY_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${LOYALTY_POSTGRES_DB_NAME}
    volumes:
      - loyalty_pgdata:/var/lib/postgresql/data
    expose:
      - "5438"
    ports:
      - "5438:5438"
    command: -p 5438

  loyalty-rabbit:
    image: rabbitmq:3.9-management
    container_name:   loyalty-rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    logging:
      driver: none
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  loyalty_pgdata:
  rabbitmq_data:
  rabbitmq_log:
  loyalty-logs:
  nginx-logs:
