"""initial migration

Revision ID: 11d619981896
Revises: 
Create Date: 2023-01-31 19:08:43.254984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d619981896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BaseDiscount',
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('group_product_id', sa.UUID(), nullable=True),
    sa.Column('discount_type', sa.Enum('all_users', 'registration', 'birthday', name='discounttype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BasePromocode',
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('promocode_type', sa.Enum('all_users', 'personal', name='promocodetype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('PersonalDiscount',
    sa.Column('discount', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('discount_status', sa.Enum('not_processed', 'in_process', 'finished', name='discountstatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['discount'], ['BaseDiscount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PersonalPromocode',
    sa.Column('promocode', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promocode'], ['BasePromocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PromocodeHistory',
    sa.Column('promocode', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('promocode_status', sa.Enum('in_process', 'finished', name='promocodestatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promocode'], ['BasePromocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PromocodeHistory')
    op.drop_table('PersonalPromocode')
    op.drop_table('PersonalDiscount')
    op.drop_table('BasePromocode')
    op.drop_table('BaseDiscount')
    # ### end Alembic commands ###
