"""initial

Revision ID: 9c1f99fa2531
Revises: 
Create Date: 2023-02-10 20:45:24.039756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1f99fa2531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_discount',
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('group_product_id', sa.UUID(), nullable=True),
    sa.Column('discount_type', sa.Enum('all_users', 'registration', 'birthday', name='discounttype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_promocode',
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('promocode_type', sa.Enum('all_users', 'personal', name='promocodetype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('personal_discount',
    sa.Column('discount_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('discount_status', sa.Enum('in_process', 'finished', 'not_processed', name='loyaltystatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['base_discount.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_id', 'user_id', name='discount_user')
    )
    op.create_table('personal_promocode',
    sa.Column('promocode_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['base_promocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocode_history',
    sa.Column('promocode_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('promocode_status', sa.Enum('in_process', 'finished', 'not_processed', name='loyaltystatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['base_promocode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocode_history')
    op.drop_table('personal_promocode')
    op.drop_table('personal_discount')
    op.drop_table('base_promocode')
    op.drop_table('base_discount')
    # ### end Alembic commands ###
