"""Update foreign keys and relationships

Revision ID: b81917e69699
Revises: 9c1f99fa2531
Create Date: 2023-02-11 19:00:16.115992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81917e69699'
down_revision = '9c1f99fa2531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_discount', 'discount_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('personal_discount_discount_id_fkey', 'personal_discount', type_='foreignkey')
    op.create_foreign_key(None, 'personal_discount', 'base_discount', ['discount_id'], ['id'], ondelete='CASCADE')
    op.alter_column('personal_promocode', 'promocode_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('promocode_user', 'personal_promocode', ['promocode_id', 'user_id'])
    op.drop_constraint('personal_promocode_promocode_id_fkey', 'personal_promocode', type_='foreignkey')
    op.create_foreign_key(None, 'personal_promocode', 'base_promocode', ['promocode_id'], ['id'], ondelete='CASCADE')
    op.alter_column('promocode_history', 'promocode_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('promocode_history_promocode_id_fkey', 'promocode_history', type_='foreignkey')
    op.create_foreign_key(None, 'promocode_history', 'base_promocode', ['promocode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocode_history', type_='foreignkey')
    op.create_foreign_key('promocode_history_promocode_id_fkey', 'promocode_history', 'base_promocode', ['promocode_id'], ['id'])
    op.alter_column('promocode_history', 'promocode_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'personal_promocode', type_='foreignkey')
    op.create_foreign_key('personal_promocode_promocode_id_fkey', 'personal_promocode', 'base_promocode', ['promocode_id'], ['id'])
    op.drop_constraint('promocode_user', 'personal_promocode', type_='unique')
    op.alter_column('personal_promocode', 'promocode_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'personal_discount', type_='foreignkey')
    op.create_foreign_key('personal_discount_discount_id_fkey', 'personal_discount', 'base_discount', ['discount_id'], ['id'])
    op.alter_column('personal_discount', 'discount_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
